### PR TITLE
Added PCB versions and David's Block Diagram

### PR DESCRIPTION
**Pull request by slinkyfish**
Only added directories for Circuitry and Block Diagrams

### CODE REVIEW

**Comment by micromouseonline** [comment]
Hi

Thank you.

Could you add a .gitignore file to the root of the repo that excludes Eagle backup files and then update the pull request with those files excluded please.

**Comment by micromouseonline** [comment]
Or maybe just to the Gantry directory?

**Comment by slinkyfish** [comment]
Has this request updated?

**Comment by slinkyfish** [comment]
Added .gitignore to Eagle Gantry directory only

**Comment by micromouseonline** [comment]
Thanks. That is much better. 
If we are to put up the gerbers at some point, we need to take care about how the gitignore treats them but I will merge this request in for now.

**Pull request merged**
